const POSITION = 'POSITION'
const MOBILE = 'MOBILE'
const CARINFO = 'CARINFO'
const BOOKTIME = 'BOOKTIME'
const PRICE = 'PRICE'
const SERVICEPROJECT = 'SERVICEPROJECT'
const SERVICE = 'SERVICE'
const CAPABILITYTYPE = 'CAPABILITYTYPE'
const STORES = 'stores'
const STOREINFO = 'storeInfo'
const ADDRESSREMARK = 'addressRemark'
export {
  POSITION,
  MOBILE,
  CARINFO,
  BOOKTIME,
  PRICE,
  SERVICEPROJECT,
  SERVICE,
  CAPABILITYTYPE,
  STORES,
  STOREINFO,
  ADDRESSREMARK
}